
spring:
  config:
    activate:
      on-profile: test

  h2:
    console:
      enabled: true

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  datasource:
    url: jdbc:h2:mem://localhost/~/users;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
